import type { NormalizeOAS, OASModel, OASOutput, OASRequestParams } from 'fets'
import type oas from './autoGenerated/openapiSpec'

type OAS = NormalizeOAS<typeof oas>

export type IGetNotesRequest = OASRequestParams<OAS, '/notes', 'get'>
export type IGetNotesResponse = OASOutput<OAS, '/notes', 'get'>
export type IPostNotesRequest = OASRequestParams<OAS, '/notes', 'post'>
export type IPostNotesResponse = OASOutput<OAS, '/notes', 'post'>
export type IDeleteNotesRequest = OASRequestParams<OAS, '/notes', 'delete'>
export type IDeleteNotesResponse = OASOutput<OAS, '/notes', 'delete'>
export type IGetNoteRequest = OASRequestParams<OAS, '/notes/{_id}', 'get'>
export type IGetNoteResponse = OASOutput<OAS, '/notes/{_id}', 'get'>
export type IPutNoteRequest = OASRequestParams<OAS, '/notes/{_id}', 'put'>
export type IPutNoteResponse = OASOutput<OAS, '/notes/{_id}', 'put'>
export type IPostAuthSignUpRequest = OASRequestParams<OAS, '/auth/sign-up', 'post'>
export type IPostAuthSignUpResponse = OASOutput<OAS, '/auth/sign-up', 'post'>
export type IPostAuthSignInRequest = OASRequestParams<OAS, '/auth/sign-in', 'post'>
export type IPostAuthSignInResponse = OASOutput<OAS, '/auth/sign-in', 'post'>
export type IDeleteUserRequest = OASRequestParams<OAS, '/user', 'delete'>
export type IDeleteUserResponse = OASOutput<OAS, '/user', 'delete'>
export type IGetUserRequest = OASRequestParams<OAS, '/user', 'get'>
export type IGetUserResponse = OASOutput<OAS, '/user', 'get'>
export type IPutUserInfoRequest = OASRequestParams<OAS, '/user/info', 'put'>
export type IPutUserInfoResponse = OASOutput<OAS, '/user/info', 'put'>
export type IPutUserPasswordRequest = OASRequestParams<OAS, '/user/password', 'put'>
export type IPutUserPasswordResponse = OASOutput<OAS, '/user/password', 'put'>

export type NoteNew = OASModel<OAS, 'NoteNew'>
export type NoteCreated = OASModel<OAS, 'NoteCreated'>
export type UserNew = OASModel<OAS, 'UserNew'>
export type HTTPErrorBody = OASModel<OAS, 'HTTPErrorBody'>
export type ValidateErrorBody = OASModel<OAS, 'ValidateErrorBody'>