import { join } from "path"
import { existsSync, mkdirSync, writeFileSync } from "fs";
import openapiSpec from "../../build/swagger.json"

let tsFileContent = `export default ${JSON.stringify(openapiSpec, null, 4)} as const`
let typesFolder = join(process.cwd(), 'test', 'types', 'cornellNotepadService', 'autoGenerated')
if (!existsSync(typesFolder)) {
    mkdirSync(typesFolder, { recursive: true })
}
const specFilePath = join(typesFolder, 'openapiSpec.ts')
writeFileSync(specFilePath, tsFileContent, { encoding: 'utf8' })