name: Test

on:
  pull_request:

jobs:
  test:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test
        run: docker compose -f ./docker-compose.yaml -f ./docker-compose.test.yaml up test-client --exit-code-from test-client
        
      - name: Cleanup
        if: ${{ !cancelled() }}
        run: docker compose -f ./docker-compose.yaml -f ./docker-compose.test.yaml down --rmi local
