name: Test

on:
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if version bumped
        uses: del-systems/check-if-version-bumped@v1.3
        
      - name: Test
        run: docker compose -f ./docker-compose.yaml -f ./docker-compose.test.yaml up test-client --exit-code-from test-client
        
      - name: Cleanup
        if: ${{ !cancelled() }}
        run: docker compose -f ./docker-compose.yaml -f ./docker-compose.test.yaml down --rmi local
